language: go

go: 
 - 1.3.3
 - 1.4.2
 - 1.5.1
 - release
 - tip

before_script:
  - go get -v github.com/stretchr/testify/assert
  - go get


  
script:
 - go test -v ./...


deploy:
  provider: releases
  api-key: e238b350d9d049def9dbe67ce0e0d2063f5356dc
  file_glob: true
  file: /*
  skip_cleanup: true
  on:
    tags: true