language: go

go: 
 - 1.8.0
 - tip

install:
  - go get -v github.com/stretchr/testify/assert

before_script:
  - go get

script:
 - go test -v ./...
 - docker build -f Dockerfile -t go-todo-rest .
 - docker push brandonvanwijk/go-todo-rest
