language: go

sudo: required


services:
  - docker

before_install:
  - go get github.com/mattn/goveralls

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build -f operations/docker/Dockerfile.test -t go-todo-rest:test .
  - docker build -f operations/docker/Dockerfile -t brandonvanwijk/go-todo-rest:latest .
  - mkdir coverage
  - docker run --rm go-todo-rest:test go test -v -covermode=count -coverprofile=coverage/coverage.out
  - goveralls -coverprofile=coverage/coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - docker push brandonvanwijk/go-todo-rest:latest 

after_script:
  - docker rmi go-todo-rest:test
  - docker rmi brandonvanwijk/go-todo-rest:latest